---
title: "Portal Forecast"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(PortalDataSummaries)
source("forecast_tools.R")
```

## Total Abundance Forecast

This is the forecast for next month's sampling of rodents at Portal.

```{r, echo=FALSE, message=FALSE, warning=FALSE}
obs_data = PortalDataSummaries::abundance()
obs_data$total = rowSums(select(obs_data, -period))
new_moon_file = PortalDataSummaries::FullPath('PortalData/Rodents/moon_dates.csv', 
                                                  '~')
new_moons = read.csv(new_moon_file)
obs_data_newmoon = inner_join(obs_data, new_moons, by = c("period" = "Period"))
#for_data = read.csv("predictions/2017-02-24Allforecasts.csv")

for_data = compile_forecasts() %>%
  dplyr::filter(level == 'All', model == 'Ensemble', date == max(date))

most_recent_forecast = max(for_data$date)
for_data = filter(for_data, date == most_recent_forecast)

for_data$model = "ensemble"

forecast_viz(obs_data = obs_data_newmoon,
             obs_date_col_name = "NewMoonNumber",
             obs_val_col_name = "total",
             for_data = for_data,
             for_date_col_name = "NewMoonNumber",
             for_val_col_name = "estimate",
             for_model_name = "ensemble",
             for_lowerpi_col_name = "LowerPI",
             for_upperpi_col_name = "UpperPI",
             start_newmoon = 300)
```

## Species-Level Forecasts

```{r speciesforecasts, echo=FALSE, message=FALSE, warning=FALSE}
source("forecast_tools.R")

data = compile_forecasts()
ensemble = dplyr::filter(data, level == 'All', model == 'Ensemble', date == max(date))
sp_predictions = get_sp_predicts(ensemble, 'All', lead_time = 1)
plot_data(sp_predictions)
```
```{r highabund_ts_forecasts, echo=FALSE, message=FALSE, warning=FALSE}
most_abund_sp = sp_predictions %>% 
  filter(species != 'total') %>% 
  arrange(desc(estimate)) %>% 
  head(3) %>% 
  select(species)

for (species in as.vector(most_abund_sp$species)) {
  species_forecast = forecast_viz(obs_data = obs_data_newmoon,
               obs_date_col_name = "NewMoonNumber",
               obs_val_col_name = species,
               for_data = for_data,
               for_date_col_name = "NewMoonNumber",
               for_val_col_name = "estimate",
               for_model_name = "ensemble",
               for_lowerpi_col_name = "LowerPI",
               for_upperpi_col_name = "UpperPI",
               start_newmoon = 300)
  plot(species_forecast)
}
```

