---
title: "Report - Latest Rodent Data"
---
Here's the most recent actual data (blue) compared to the forecast performed right before data collection (black, with error bars)
```{r, echo=FALSE, message=FALSE, warning=FALSE}
source("tools/forecast_tools.R")
library(portalr)

# get most recent rodent data
rodents = abundance("repo", clean=FALSE, shape='flat', level='treatment', length='longterm')
most_recent_period = max(rodents$period)
observed = dplyr::filter(rodents, period == most_recent_period, treatment=='control')

# get new moon number associated with this period
newmoons_table = read.csv(text = RCurl::getURL("https://raw.githubusercontent.com/weecology/PortalData/master/Rodents/moon_dates.csv"))
newmoons_table$censusdate = as.Date(newmoons_table$censusdate,format='%Y-%m-%d')
moon_code = dplyr::filter(newmoons_table,period==most_recent_period) %>% select(newmoonnumber) %>% as.integer()
most_recent_date = dplyr::filter(newmoons_table,period==most_recent_period) %>% dplyr::pull(censusdate)

# get most recent forecast prior to data collection
files = data.frame(names = list.files(path = './forecasting/predictions', pattern = '*forecasts.csv'))
files$filedates = as.Date(substr(files$names,1,10),format='%Y-%m-%d')
latest_forecast = dplyr::filter(files,filedates<most_recent_date) %>% tail(1)

data = read.csv(paste('forecasting/predictions/',latest_forecast$names,sep=''),na.strings = '')

ensemble = dplyr::filter(data, level == 'Controls', model == 'Ensemble', newmoonnumber==moon_code)
sp_predictions = get_sp_predicts(ensemble, 'Controls', lead_time = 1)


joined_data = left_join(sp_predictions, observed, by = "species")
joined_data[is.na(joined_data)] = 0
joined_data[joined_data$species=='total','abundance'] = sum(joined_data$abundance,na.rm=T)
joined_data[joined_data$species=='total','period'] = most_recent_period

sp_predict = plot_species_forecast(sp_predictions,title=paste0(sp_predictions$forecast_date[2], ": Control plots"))  
sp_predict = sp_predict + geom_point(data = joined_data, mapping = aes(x = abundance, y = species),
             color = "blue")
plot(sp_predict)
```

```{r, echo=FALSE, message=FALSE, warning=FALSE}
source("tools/forecast_tools.R")
library(portalr)

# get most recent rodent data
rodents = abundance("repo", clean=FALSE, shape='flat')
most_recent_period = max(rodents$period)
observed = dplyr::filter(rodents, period == most_recent_period)

# get new moon number associated with this period
newmoons_table = read.csv(text = RCurl::getURL("https://raw.githubusercontent.com/weecology/PortalData/master/Rodents/moon_dates.csv"))
newmoons_table$censusdate = as.Date(newmoons_table$censusdate,format='%Y-%m-%d')
moon_code = dplyr::filter(newmoons_table,period==most_recent_period) %>% select(newmoonnumber) %>% as.integer()
most_recent_date = dplyr::filter(newmoons_table,period==most_recent_period) %>% dplyr::pull(censusdate)

# get most recent forecast prior to data collection
files = data.frame(names = list.files(path = './forecasting/predictions', pattern = '*forecasts.csv'))
files$filedates = as.Date(substr(files$names,1,10),format='%Y-%m-%d')
latest_forecast = dplyr::filter(files,filedates<most_recent_date) %>% tail(1)

data = read.csv(paste('forecasting/predictions/',latest_forecast$names,sep=''),na.strings = '')

ensemble = dplyr::filter(data, level == 'All', model == 'Ensemble', newmoonnumber==moon_code)
sp_predictions = get_sp_predicts(ensemble, 'All', lead_time = 1)


joined_data = left_join(sp_predictions, observed, by = "species")
joined_data[is.na(joined_data)] = 0
joined_data[joined_data$species=='total','abundance'] = sum(joined_data$abundance,na.rm=T)
joined_data[joined_data$species=='total','period'] = most_recent_period

sp_predict = plot_species_forecast(sp_predictions,title=paste0(sp_predictions$forecast_date[2], ": All plots"))  
sp_predict = sp_predict + geom_point(data = joined_data, mapping = aes(x = abundance, y = species),
             color = "blue")
plot(sp_predict)
```